# Configuration for PR labeler v5
# Add labels to PRs based on file changes and branch patterns

# Documentation changes
documentation:
  - changed-files:
    - any-glob-to-any-file: ['*.md', 'docs/**/*', 'README*', 'CHANGELOG*', 'CONTRIBUTING*', 'LICENSE*']

# Feature development
feature:
  - changed-files:
    - any-glob-to-any-file: ['src/**/*', 'lib/**/*']
  - head-branch: ['^feature', '^feat']

# Bug fixes
bug:
  - head-branch: ['^fix', '^bugfix', '^hotfix']

# Tests
test:
  - changed-files:
    - any-glob-to-any-file: ['**/*test*', '**/*spec*', '__tests__/**/*', 'test/**/*', 'tests/**/*']

# Dependencies
dependencies:
  - changed-files:
    - any-glob-to-any-file: ['package.json', 'package-lock.json', 'yarn.lock', 'npm-shrinkwrap.json']

# CI/CD and automation
ci:
  - changed-files:
    - any-glob-to-any-file: ['.github/**/*', '*.yml', '*.yaml', '.gitignore', '.dockerignore']

# Build and tooling
build:
  - changed-files:
    - any-glob-to-any-file: ['webpack.config.js', 'rollup.config.js', 'tsconfig.json', 'jest.config.js', 'eslint.config.js', '.prettierrc*', '.editorconfig', 'dist/**/*', 'build/**/*']

# Maintenance/chores
chore:
  - head-branch: ['^chore', '^maintenance']

# Configuration files
config:
  - changed-files:
    - any-glob-to-any-file: ['*.config.js', '*.config.ts', '.env*', '*.json']
