# GitHub Action metadata for setup-liquibase
# This action downloads and installs Liquibase (OSS or Pro) for use in GitHub Actions workflows

name: 'Setup Liquibase'
description: 'Set up your GitHub Actions workflow with a specific version of Liquibase'
author: 'Liquibase'

# GitHub Marketplace branding
branding:
  icon: 'database'  # Database icon representing Liquibase's purpose
  color: 'blue'     # Blue color matching Liquibase brand

# Input parameters that users can configure when using this action
inputs:
  version:
    description: 'Specific version of Liquibase to install (e.g., "4.32.0"). Must be 4.32.0 or higher.'
    required: true
  
  edition:
    description: 'Edition to install: "oss" (Open Source) or "secure" (Secure edition with additional features). "pro" is supported for backward compatibility. For Secure/Pro editions, set LIQUIBASE_LICENSE_KEY environment variable when running Liquibase commands.'
    required: true

  download-url-base:
    description: 'Optional custom base URL for downloading Liquibase binaries from internal or alternative sources (e.g., Nexus, Artifactory). Use {version} as placeholder for version number, {platform} for platform (windows/unix), and {extension} for file extension (zip/tar.gz). Example: https://internal-repo.company.com/liquibase/{version}/liquibase-{version}.{extension}. Can also be set via LIQUIBASE_DOWNLOAD_URL_BASE environment variable.'
    required: false
    default: ''


# Output values that other workflow steps can use
outputs:
  liquibase-version:
    description: 'The version of Liquibase that was installed'
  
  liquibase-path:
    description: 'The file system path where Liquibase was installed and added to PATH'

# Action execution configuration
runs:
  using: 'node20'        # Use Node.js 20 runtime
  main: 'dist/index.js'  # Entry point for the compiled action