name: Enterprise Liquibase with AWS Secrets Manager
on: [push]

jobs:
  deploy-with-aws-secrets:
    runs-on: ubuntu-latest
    steps:
      # Configure AWS credentials using OIDC or roles
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1

      - uses: actions/checkout@v4

      # Setup Liquibase Pro edition  
      - name: Setup Liquibase Pro
        uses: liquibase/setup-liquibase@v1
        with:
          version: '4.32.0'
          edition: 'pro'

      # Install AWS Secrets Manager extension for license retrieval
      - name: Install AWS Secrets Manager Extension
        run: |
          wget -O liquibase-aws-secretsmanager.jar \
            https://repo1.maven.org/maven2/org/liquibase/ext/liquibase-secretsmanager-aws/1.0.6/liquibase-secretsmanager-aws-1.0.6.jar

      # Method 1: Using --license-key parameter with vault syntax
      - name: Database Update with Vault License
        run: |
          liquibase \
            --classpath=liquibase-aws-secretsmanager.jar \
            --license-key=aws-secrets,liquibase-secrets,pro-license-key \
            --url=jdbc:postgresql://localhost/mydb \
            --username=dbuser \
            --password=dbpass \
            update --changelog-file=changelog.xml

      # Method 2: Using Liquibase properties file 
      - name: Configure Liquibase Properties with Vault
        run: |
          cat > liquibase.properties << EOF
          liquibase.licenseKey=aws-secrets,liquibase-secrets,pro-license-key
          url=jdbc:postgresql://localhost/mydb
          username=dbuser
          password=dbpass
          EOF

      - name: Run Pro Commands with Properties File
        run: |
          liquibase --classpath=liquibase-aws-secretsmanager.jar update --changelog-file=changelog.xml
          liquibase --classpath=liquibase-aws-secretsmanager.jar checks run --changelog-file=changelog.xml

      # Method 3: Alternative - Retrieve secret to environment variable
      - name: Retrieve License from AWS Secrets Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            LIQUIBASE_LICENSE_KEY,liquibase-secrets,pro-license-key

      - name: Run with Environment Variable License
        run: |
          liquibase update --changelog-file=changelog.xml
          liquibase checks run --changelog-file=changelog.xml

      # Example: S3 flow files with vault integration
      - name: Install S3 Extension
        run: |
          wget -O liquibase-aws-extension.jar \
            https://repo1.maven.org/maven2/org/liquibase/ext/liquibase-aws-extension/1.0.1/liquibase-aws-extension-1.0.1.jar

      - name: Execute S3 Flow with Vault License
        run: |
          liquibase \
            --classpath=liquibase-aws-secretsmanager.jar:liquibase-aws-extension.jar \
            --license-key=aws-secrets,liquibase-secrets,pro-license-key \
            --search-path=s3://my-bucket/liquibase/resources,. \
            flow --flow-file=s3://my-bucket/liquibase/flows/production.flowfile.yaml