name: Secure Edition Usage
on: [push]

jobs:
  secure-operations:
    runs-on: ubuntu-latest
    env:
      LIQUIBASE_LICENSE_KEY: ${{ secrets.LIQUIBASE_LICENSE_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: liquibase/setup-liquibase@v2
        with:
          version: '5.0.3'
          edition: 'secure'

      - name: Run Secure Features
        run: |
          # Generate diff report
          liquibase diff-changelog \
            --reference-url=jdbc:postgresql://localhost/reference_db \
            --url=jdbc:postgresql://localhost/target_db \
            --changelog-file=diff.xml

          # Run quality checks
          liquibase checks run --changelog-file=changelog.xml
