name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  claude-review:
    uses: liquibase/build-logic/.github/workflows/claude-code-review.yml@main
    secrets: inherit

