name: PR Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub App token
        id: get-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.LIQUIBASE_GITHUB_APP_ID }}
          private-key: ${{ secrets.LIQUIBASE_GITHUB_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          permission-contents: write
          permission-actions: write
          permission-packages: write
          permission-pull-requests: write
          permission-issues: write

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.get-token.outputs.token }}

      - name: Auto-label PR
        uses: actions/labeler@v5
        with:
          repo-token: ${{ steps.get-token.outputs.token }}
          configuration-path: .github/labeler.yml
